import type { Metadata } from "next";
import dynamic from "next/dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const DynamicInstrumentationWeb = dynamic(() => import("@/app/instrumentation.web"), {
  ssr: false,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}

        <DynamicInstrumentationWeb />
      </body>
    </html>
  );
}
